//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Intelligent Steering Using Adaptive PID Controllers.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_INTELLIGENTSTEERINGUSINGADAPTIVEPIDCONTROLLERS_DIALOG 102
#define IDS_HELP_CAPTION                102
#define IDS_HELP_P_COEFFICIENT          103
#define IDS_HELP_I_COEFFICIENT          104
#define IDS_HELP_D_COEFFICIENT          105
#define IDS_ERROR_EXPLANATION           106
#define IDS_EQUATION                    107
#define IDS_TEXTURE_DIRECTORY           108
#define IDS_TARGET_TEXTURE              109
#define IDS_PID_TEXTBOX_NUMBER_FORMAT   110
#define IDS_ACCELERATION_SPEED_TEXTBOX_NUMBER_FORMAT 111
#define IDS_HELP_P_COEFFICIENT_2        112
#define IDS_HELP_I_COEFFICIENT_2        113
#define IDS_HELP_D_COEFFICIENT_2        114
#define IDS_MISSILE_TEXTURE_NO_FLAME    115
#define IDS_MISSILE_TEXTURE_FLAME_1     116
#define IDS_MISSILE_TEXTURE_FLAME_2     117
#define IDS_MISSILE_TEXTURE_FLAME_3     118
#define IDS_EXPLOSION_TEXTURE           119
#define IDS_ROTATIONAL_DRAG_NUMBER_FORMAT 120
#define IDR_MAINFRAME                   128
#define IDC_OPENGLWIN                   1000
#define IDC_RADIO_MISSILE_CONTROL_PID   1001
#define IDC_RADIO_MISSILE_CONTROL_KEYBOARD 1002
#define IDC_RADIO_TARGET_CONTROL_AUTOMATIC 1003
#define IDC_RADIO_TARGET_CONTROL_KEYBOARD 1004
#define IDC_RADIO_MISSILE_CONTROL_PID2  1005
#define IDC_RADIO_MISSILE_CONTROL_ADAPTIVE_PID 1005
#define IDC_EDIT_MISSILE_STEERING_P     1010
#define IDC_EDIT_MISSILE_STEERING_I     1011
#define IDC_EDIT_MISSILE_STEERING_D     1012
#define IDC_EDIT_MISSILE_ACCELERATION   1013
#define IDC_CHECK_PAUSE_WORLD           1014
#define IDC_EDIT_TARGET_SPEED           1015
#define IDC_EDIT_MISSILE_ROTATIONAL_DRAG 1016
#define IDC_EDIT_MISSILE_MAX_ANGULAR_ACCELERATION 1017
#define IDC_SLIDER_MISSILE_STEERING_P   1018
#define IDC_BUTTON_RESET_SLIDERS        1019
#define IDC_SLIDER_MISSILE_ACCELERATION 1020
#define IDC_SLIDER_MISSILE_STEERING_I   1021
#define IDC_SLIDER_MISSILE_STEERING_D   1022
#define IDC_SLIDER_TARGET_SPEED         1023
#define IDC_BUTTON_HELP_P_COEFFICIENT   1024
#define IDC_BUTTON_HELP_I_COEFFICIENT   1025
#define IDC_BUTTON_HELP_D_COEFFICIENT   1026
#define IDC_SLIDER_MISSILE_ROTATIONAL_DRAG 1027
#define IDC_SLIDER_MISSILE_MAX_ANGULAR_ACCELERATION 1028
#define IDC_EDIT_MISSILE_PID_OUTPUT_SCALE 1029
#define IDC_SLIDER_MISSILE_PID_OUTPUT_SCALE 1030
#define IDC_RADIO5                      1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
